name: Publishing build tools
on:
  push:
    branches:
      - master
    paths:
      - '.nuke/**'
      - '.github/**'

jobs:
  publish-build-tools:
    name: Publishing build tools
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - uses: actions/checkout@v4
      - run: |
         dotnet publish -r win-x64 -o artifacts
         dotnet publish -r linux-x64 -o artifacts
      - uses: actions/upload-artifact@v4
        with: 
          name: BuildTools
          path: artifacts
          retention-days: 90
